title: Sanchit Gupta
author: Sanchit Gupta
description: This is the offitial website of Sanchit Gupta, give knowledge and information about computer technology. It is made while learning web development. 
